RodrigoSpano/pig_commander_client

src/app/home/dashboard/page.jsx
src/app/home/help/page.jsx
src/app/home/management/page.jsx
src/app/home/profile/page.jsx
src/app/home/reports/page.jsx
src/app/home/settings/page.jsx
src/app/home/wallet/page.jsx
src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/dashboard.module.css
src/components/Help/HelpComponent.jsx
src/components/Management/ManagementComponent.jsx
src/components/Profile/ProfileComponent.jsx
src/components/Reports/ReportsComponent.jsx
src/components/Settings/SettingsComponent.jsx
src/components/Wallet/WalletComponent.jsx

la informacion de las pages vienen con la importacion del componente de cada page (fueron creados en la carpeta de components)

FEAT(client/app/home): agrega contenido a archivos de las pages de home

---

src/app/layout.js

actualmente no funciona el condicional xq lihuel tiene q hacer la page de la landing y vicky el auth

FEAT(client/layout): agrega condicional para mostarr sidebar

---

.vscode/settings.json
src/app/landing/page.jsx
src/app/layout.js
src/app/login/page.jsx
src/components/Login/LoginPage.jsx

Login le falta funcionalidad, iconos en input. Ademas se soluciona problema del layout

login sin funcionalidades y arreglo error del layout

---

src/components/Login/LoginPage.jsx

Cambio a u color mas oscuro debido a cambioas en el css global

cambio color bg del input

---

src/app/signup/page.jsx
src/components/SignUp/SignUp.jsx

Guardo esto, para que mati pueda hacer el cambio de nombre del archivo.

primera parte de signup

---

.vscode/settings.json
src/app/layout.js
src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/dashboard.module.css

Feature(client/dashboard):Tamaños responsive-boxes

---

.gitignore
src/server/db.json
src/server/package-lock.json
src/server/package.json

Instalamos dependencia: json-server en carpeta "server" dentro de src.
hicimos un npm init en carpeta server.

feature(CLIENT/hardcodeoDB): "Agregamos db hardcodeada"

---

src/components/Dashboard/DashboardComponent.jsx
src/components/Pagination/PaginationComponent.jsx
src/components/Transactions/TransactionsComponent.jsx
src/customHooks/usePagination.jsx

crea hook de pagination
crea componente donde mostarr botones con las funcionalidades
crea componente de transactions para traer los pedazos del estado global (ahora esta hardcodeado)

Feat(cleint/pagination): crea paginado

---

.vscode/settings.json
src/components/Login/LoginPage.jsx
tailwind.config.js

Login controlado. También agregué un color a configTailwind .

login controlado

---

src/components/Landing/HeroSection.jsx
src/components/Landing/NavBar.jsx

feat(client/landing): links a botones

---

.vscode/settings.json
src/components/Login/LoginPage.jsx
src/components/SignUp/SignUp.jsx

signup validado y ruta link a login

signup validado y ruta link a login

---

src/components/SignUp/SignUp.jsx
src/customHooks/useSignup.jsx

creacion del useSignUp

---

src/components/Login/LoginPage.jsx
src/components/SignUp/SignUp.jsx
src/customHooks/useLogin.jsx

Navegación al dashboard desde login

feat(client/useLogin): navegation to dashboard

---

src/app/layout.js
src/customHooks/useLogin.jsx
src/redux/actions/userActions.js
src/redux/features/transactionsSlice.js
src/redux/features/userSlice.js

#72 
login req to back
redirect to dashboard when logged

64 feat/clientredux global state slice and actions

---

src/components/SideRight/SideRight.jsx
src/customHooks/useSignup.jsx

#74 
create user in db from signup page in react

feat(client/auth): signup req to back

---

src/components/Login/LoginPage.jsx
src/components/SignUp/SignUp.jsx
src/customHooks/useLogin.jsx
tailwind.config.js

Realice cambios de css tanto en el login como en el signup. Quedan algunos detalles a charlar.

feat(client/login and signup): retocando detalles 

---

src/components/Login/LoginPage.jsx
src/components/SignUp/SignUp.jsx
src/customHooks/useLogin.jsx
src/customHooks/useSignup.jsx
tailwind.config.js

Paso los focus a los hooks de login y signup

feat(client/login/signup/useLogin/useSignUp): paso los focus a los hooks de login y signup

---

src/components/SearchBar/SearchBarComponent.jsx
src/components/Transactions/TransactionsComponent.jsx
src/customHooks/usePagination.jsx
src/redux/features/monthTransactionsSlice.js

falta ordenamiento por amount y filtro por category

feat(client/transactions): ordenamientos, searchbar y titulo

---

package-lock.json
package.json
src/components/Transactions/TransactionsComponent.jsx
src/customHooks/usePagination.jsx
src/customHooks/useTransactionDetail.jsx

clicj a una transaction para que salga la sweetalert
faltan estilos que no se como darselos

feat(client/transactionsDetail): cree los detalles de las transactions

---

src/redux/actions/monthTransactionsActions.js
src/redux/actions/transactionsActions.js
src/redux/features/monthTransactionsSlice.js
src/redux/features/transactionsSlice.js

peticiones al back del crud de transactions
peticiones al back del crud de transactions del mes
creacion de filtros por type => expense o income
reset filters action

93 feat/clientredux get info from back server

---

src/components/Landing/NavBar.jsx
src/components/Transactions/TransactionsComponent.jsx

correction in navlinks hovers
image optimizations

chore(client/landing): optimization and corrections

---

src/customHooks/useLogin.jsx
src/customHooks/useSignup.jsx
src/redux/actions/userActions.js

using swetalerts for errors and success alerts
handling errors

(client/alerts): handle errors and alerts)

---

src/redux/actions/monthTransactionsActions.js
src/redux/actions/userActions.js

cuando se logea guardo el token en el session storage para que dure lo que dura la session del navegador

108 hotfix/client connection backend session connection

---

src/components/Dashboard/DashboardComponent.jsx
tailwind.config.js

fix(client/dashboard): correccion de estilos

---

src/app/layout.js
src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcomps/MoneyCard.jsx
src/components/Pagination/PaginationComponent.jsx
src/components/SideBar/SideBarComponent.jsx
src/components/Transactions/TransactionsComponent.jsx
src/redux/actions/userActions.js
src/redux/features/monthTransactionsSlice.js
src/redux/features/savingsSlice.js
src/redux/features/userSlice.js
src/utils/helper/monthTransactions.js

basicamente si recargas la pagina no perdes la info de usuario
se borra el token cuando logout.onclick

124 chore/clientuser optimizar carga de usuario

---

src/components/Login/LoginPage.jsx
src/customHooks/useLogin.jsx
src/customHooks/useSignup.jsx
src/redux/actions/inversionsActions.js
src/redux/actions/monthTransactionsActions.js
src/redux/actions/savingsActions.js
src/redux/actions/transactionsActions.js
src/redux/actions/userActions.js

elimine console logs
maneje los errores con lo que se manda del back con sweetalerts

feat(client/actions-customHooks): manejo de errores

---

src/components/FormWallet/FormWallet.jsx
src/customHooks/useFormWallet.jsx

feat(client/wallet/form): validations

---

src/components/Management/ManagementComponent.jsx
src/components/Management/subcomps/GraphComponent.jsx
src/components/Management/subcomps/InvestmentFormComponent.jsx
src/components/Management/subcomps/SavingFormComponent.jsx
src/components/Management/subcomps/subcomps_forms/imputs.jsx
src/components/Management/subcomps/subcomps_graphs/Option_one_component.jsx
src/components/Management/subcomps/subcomps_graphs/Option_two_component.jsx
src/components/Wallet/WalletComponent.jsx

Me falto meter los graficos y el advise. Esta la logica de cambio con el select. Falta estilizar el modulo de graficos.

feature(client/management):"Modularizacion de graphs y css"

---

src/components/Login/LoginPage.jsx
src/components/SignUp/SignUp.jsx

feat(client/login/signup):autenticacion de terceros

---

src/components/Dashboard/subcomps/UserCard.jsx
src/components/Profile/ProfileComponent.jsx
src/components/Profile/becomePremiumHandler.js
src/redux/store.js

feature(buttom/premium):logic of bottom MP

---

src/components/FormWallet/FormWallet.jsx
src/components/MyBalance/MyBalance.jsx

Parte final de css en Transactions, también agregué la linea fucsia arriba del form. Las funcionalidades van despues de los filtros.

feat(client/wallet/transactions):parte final css

---

package-lock.json
package.json
src/app/home/wallet/page.jsx
src/app/layout.js
src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcomps/StatsContainer.jsx
src/components/Profile/ProfileComponent.jsx
src/components/SideBar/SideBarComponent.jsx
src/components/SideBar/Subcomponents/LogOut.jsx
src/components/Transactions/TransactionsComponent.jsx
src/redux/actions/userActions.js

cambie el storage de los tokens, ahora se guardan en cookies para poder utilizarlo en el middleware
descargue una dependencia, react-cookie asi que hagan npm i

chore(client/tokens): change tokens storage to cookies

---

src/components/Help/HelpComponent.jsx
src/components/MyBalance/MyBalance.jsx
src/components/Profile/ProfileComponent.jsx

info sensible en balance
'use client' en profile para que renderice el componente
Frequently asked questions en help

feat(client/MyBalance-Profile-Help): changes

---

src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcomps/MyJournalCard.jsx
src/redux/actions/journalAction.js
src/redux/features/journalSlice.js
src/redux/store.js

Creacion del reducer,
creacion del action,
componente journal.
Falta estilado

Feature(CLIENT/Dashboard/myJournal): "traer de la api la info de las noticias"

---

src/app/home/wallet/page.jsx
src/components/FormWallet/FormWallet.jsx
src/customHooks/useFormWallet.jsx
src/redux/actions/transactionsActions.js
src/redux/features/transactionsSlice.js

Funciona tanto incomes y expenses. Hice un pequeño cambio en las actions, agregue esta linea en cada action: 
-const { token, ...expenseInfo } = payload;
-const { token, ...incomeInfo } = payload;
Y en el async puse (payload);

feat(client/formwallet):funcionalidad

---

src/components/Dashboard/subcomps/MyJournalCard.jsx
src/components/Help/HelpComponent.jsx
src/redux/actions/journalAction.js
src/redux/features/journalSlice.js

fix(client/news): news

---

src/app/globals.css
src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcomps/MyJournalCard.css
src/components/Dashboard/subcomps/MyJournalCard.jsx
src/components/Dashboard/subcomps/StatsContainer.jsx
src/components/Transactions/TransactionsComponent.jsx

las cards de las news para q no se rompa si tiene menos info y la altura de la transaccion por ahora

fix(dashboard/news/transactions): bugs

---

src/app/home/management/page.jsx
src/components/Dashboard/subcomps/StatsContainer.jsx
src/redux/actions/savingsActions.js
src/redux/features/inversionsSlice.js
src/redux/store.js

ya no se modifican las moneyCards del dashboard cuando se filtran las transacciones
hice dispatch de savings e inversions en management page

chore/fix(client/dashboard): transactions do not filters in moneyCard

---

src/components/FormWallet/FormWallet.jsx
src/components/Landing/Features/FeaturesPage.jsx
src/customHooks/useFormWallet.jsx

feat(client/walletForm):toast 

---

src/components/Transactions/subcomps/PermanentFilter.jsx
src/components/Wallet/subcomps/FilterAllTransactions.jsx

fix(client/wallet-transactions): agrega option deshabilitada en los selects de los filtros

---

package-lock.json
package.json
src/app/layout.js
src/components/SideBar/SideBarComponent.jsx
src/components/SideBar/Subcomponents/RateApp/RateApp.jsx
src/components/SideBar/Subcomponents/RateApp/Sobcomponents/RateAppDescription.jsx
src/components/SideBar/Subcomponents/RateApp/Sobcomponents/RateStars.jsx
src/components/SideBar/Subcomponents/RateApp/Sobcomponents/TextAreaModal.jsx
tailwind.config.js

Hice el componente Rate app, esta situado en el SideBar, y sirve para que el usuario pueda dar una opinion sobre la app

Feature(Client/Dashboard): RateApp

---

src/components/SignUp/SignUp.jsx

agrega ojo para ver la password en register

feat(client/signup): info sensible password

---

src/components/Dashboard/subcomps/BalanceCard.jsx
src/customHooks/useTransactionDetail.jsx
src/redux/actions/transactionsActions.js
src/redux/features/transactionsSlice.js

Además arreglo error del balance en Dashboard

feat(client/wallet/transactions):delete

---

package-lock.json
package.json
src/app/home/dashboard/page.jsx
src/components/CustomButtons/BackButton.jsx
src/components/DashboardAdmin/DashboardAdminComponent.jsx

falta la tabla de usuarios con su informacion

feat(client/dashboardadmin): maquetado

---

package-lock.json
src/components/Dashboard/subcomps/MyGraph/MyGraph.jsx
src/components/FormWallet/FormWallet.jsx
src/customHooks/useFormWallet.jsx
src/utils/helper/automateTransactions.js

crear transacciones automatizadas en wallet component

240 feat/clientformwalletautomatized

---

src/components/Dashboard/DashboardComponent.jsx
src/components/Help/HelpComponent.jsx
src/components/Loader/LoaderComponent.jsx
src/components/Management/ManagementComponent.jsx
src/components/Profile/ProfileComponent.jsx
src/components/Reviews/ReviewsComponent.jsx
src/components/Settings/SettingsComponent.jsx
src/components/Wallet/WalletComponent.jsx

agrega loader en todos los componentes de la sidebar

FEAT(client/dashboard): loader

---

src/components/Dashboard/DashboardComponent.jsx
src/components/SideBar/SideBarComponent.jsx

fix(client): loader

---

src/components/Dashboard/subcomps/BalanceCard.jsx
src/components/MyBalance/MyBalance.jsx

fix(my-balance): arregle el renderizado de my balance

---

src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcompsEs/BalanceCardEs.jsx
src/components/Dashboard/subcompsEs/StatsContainerEs.jsx
src/components/Dashboard/subcompsEs/UserCardEs.jsx
src/components/Profile/ProfileComponentEs.jsx
src/components/SideBar/SideBarComponent.jsx
src/components/SideBar/Subcomponents/Dashboard.jsx
src/components/Transactions/TransactionsComponentEs.jsx

ajuste el width dela side bar para que quede del mismo tamaño en el cambio de idioma y arregle las stats traducidas
falta ajustar el width de las secciones en la sidebar

feat(client/sidebar-dash): bar width & spanish stats

---

src/components/Help/HelpComponent.jsx
src/components/Transactions/TransactionsComponentEs.jsx

preguntas frecuentes taducidas

feat(client/help): faq traducidas

---

src/components/DashboardAdmin/AdminTable/AdminTableEs.jsx
src/components/DashboardAdmin/AdminTable/data.js
src/components/DashboardAdmin/AdminTable/dataEs.js
src/components/DashboardAdmin/DashboardAdminComponent.jsx
src/components/DashboardAdmin/TotalUsersCards/UsersCardsEs.jsx
src/components/DashboardAdmin/User/UserSectionEs.jsx
src/components/SideBar/SideBarComponent.jsx

admin dashboard traducida (el plan y status del usuario no se puede traducir porque es el valor de una propiedad que viene desde el back)

feat(client/admindash): traduccion

---

src/components/DashboardAdmin/AdminTable/UserDetailModal.jsx
src/redux/features/adminSlice.js

fix(client/admin): redux ban logica

---

src/components/Management/ManagementComponent.jsx
src/components/Management/subcomps/InvestmentFormComponent.jsx
src/components/Management/subcomps/NavComponent.jsx
src/components/Management/subcomps/SelectMethod.jsx
src/components/Management/subcomps/subcomps_graphs/Option_one_component.jsx
src/components/Management/subcomps/subcomps_graphs/subcomps_module/Signs.jsx
src/components/Management/subcomps/subcomps_graphs/subcomps_module/TableComponent.jsx
src/components/MyBalance/BalancesCard.jsx
src/components/Transactions/TransactionsComponent.jsx
src/components/Transactions/TransactionsComponentEs.jsx
src/components/Wallet/SpendingCategoriesComponent.jsx
src/customHooks/useDetailInv.jsx
src/customHooks/useInvestmentForm.jsx
src/redux/actions/inversionsActions.js
src/redux/actions/transactionsActions.js
src/redux/features/inversionsSlice.js
src/utils/helper/automateTransactions.js
src/utils/helper/inversionsFuncs.js

refactorice y modularice la pagina de management, y arregle algunas cositas

332 chore/clientinvestments code refactor

---

src/components/DashboardAdmin/AdminTable/UserDetailModal.jsx
src/components/DashboardAdmin/AdminTable/subComponents/HeaderDetail.jsx
src/components/DashboardAdmin/AdminTable/subComponents/SectionDetail.jsx

estilos al modal de los detalles de cada usuario

feature(detail/users/admin): estilos al modal detail de users

---

src/components/Dashboard/subcomps/MyGraph/MyGraph.jsx

352 fix/donut fixing donut numbers

---

src/components/LanguageSwitch/LanguageSwitch.jsx

al virgo de lihue le falto declarar dispatch

fix(client/profile): dispatch setlanguage

---

src/components/Landing/Footer.jsx
src/components/LandingEs/FooterEs.jsx

arregle links del footer y navbar

fix(footer/links): arregle links del footer y navbar

---

src/app/layout.js
src/app/recovery/page.jsx
src/components/Login/LoginPage.jsx
src/components/Login/subcomps/ForgotPasswordModal.jsx
src/components/forgotPasss/Container.jsx

forgot passsword functionality in front

380 (feat/forgot): password login

---

src/components/Login/LoginPage.jsx
src/components/Login/subcomps/ForgotPasswordModal.jsx
src/components/Login/subcompsEs/ForgotPasswordModalEs.jsx

feat(client/forgotyourpasswordes): traduccion

---

src/components/MyBalance/MyBalance.jsx
src/components/Wallet/FormWallet/FormWallet.jsx
src/components/Wallet/subcomps/FilterAllTransactions.jsx
src/customHooks/useFormWallet.jsx

fix(inputs/wallets): inputs vacios

---

src/components/SideBar/Subcomponents/RateApp.jsx

fix(client/postreview) swal fire en el review

---

src/components/Dashboard/DashboardComponent.jsx
src/components/Dashboard/subcomps/MyJournalCard.jsx
src/components/Dashboard/subcomps/WelcomeCard.jsx
src/components/Dashboard/subcompsEs/MyGraphEs/EmptyDonutComponentEs.jsx
src/components/Dashboard/subcompsEs/MyJournalCardEs.jsx
src/components/Dashboard/subcompsEs/WelcomeCardEs.jsx
src/components/SideBar/SideBarComponent.jsx
src/components/Transactions/TransactionsComponent.jsx
src/components/Transactions/TransactionsComponentEs.jsx

fix(dashboard/styles): arreglas algunos bugs

---

src/components/Management/AdviceComponent.jsx
src/components/Management/subcomps/InvestmentFormComponent.jsx
src/components/Management/subcomps/SavingFormComponent.jsx
src/components/Management/subcomps/SelectMethod.jsx
src/components/Management/subcomps/subcomps_forms/imputs.jsx
src/components/Management/subcomps/subcomps_graphs/AddSavForm.jsx
src/components/Management/subcomps/subcomps_graphs/Option_one_component.jsx
src/components/Management/subcomps/subcomps_graphs/Option_two_component.jsx
src/components/Management/subcomps/subcomps_graphs/subcomps_module/SavingsTableComponent.jsx

fix(management):arreglar-bugs-de-estilos-de-publicidad

---

src/components/SignUp/SignUp.jsx
src/components/forgotPasss/Container.jsx
src/customHooks/useForgotPassword.jsx

Además creación de un hook para la misma

Feat(client/forgotPassword) add design
